
# Spatial transcriptomic analysis of cavitary lesions in Mycobacterium tuberculosis lungs

## Description
Tuberculosis is a global epidemic caused by Mycobacterium Tuberculosis (Mtb), infecting 10.6 million people worldwide in 2022. A hallmark of pulmonary TB is the formation of cavitary lesions in ~30-85% of patients. Those cavities have been associated with heightened Mtb replication and irreparable lung damage. The underlying mechanisms for cavity formation are poorly described. Preliminary human data suggests that progression from granuloma to cavity is dependent on highly localized signals even within the same subject. The balance of pro- and anti-inflammatory signals in situ has been suggested to contribute to cavity formation.  Jeffrey Collins and his team are leading the charge in attempting to analyze spatial transcriptomic datasets from Mtb-infected human and NHP lung tissue to define immune-metabolic mechanisms associated with cavity formation.

## Data
Visium slides were generated from lung sections of NHP and humans infected with Mtb. Data was processed by Hadiya in Ashish Sharma's laboratory, then sequenced by the Yerkes Genomics core at Emory University. Raw data was preprocessed using spaceranger v2.0 with high resolution images when deemed satisfactory. Otherwise, the default CytAssist image was used.

## Goals
  1. Preprocess, normalize and explore their data, from Human and NHP.
  2. Perform dimension reduction and clustering
  3. Integrate across multiple sections, across species
  4. Identify spatially variable genes associated with different structures such as granulomas, fibromas, etc.
  5. Deconvolute cell type frequencies per spot,  and gene expression per fraction
  6. Perform pathway analysis for both immune and metabolic signatures"
